# top level stuff you probably don't need to touch
highlighter: pygments
markdown: rdiscount
rdiscount:
  extensions: [smart]
permalink: /:title.html
paginate: 5
port: 3000
safe: true

# edit here to achieve your personal greatness
url: http://marcohab.me
baseurl:
title: Marco Antônio Habitzreuter
author: Marco Antônio Habitzreuter
description: Página pessoal
avatar: profile.png
email: marcoahab@gmail.com
github: marcoahab
twitter:
facebook: habitzm
linkedin: marcoahab
disqus: marcoahab
google_analytics:
